/* Topic: Les pronoms — the little world of the lady of mirrors.
   Built from the user's sheet « 人称代词复习与练习 » (pronouns, demonstratives, possessives).
   Every entry: fr + zh + en. Optional: note {zh,en}, alt [other accepted answers]. */
FL.registerTopic({
  id: 'pronoms',
  emoji: '◐',
  title: { fr: 'Les pronoms', zh: '代词与限定词', en: 'Pronouns' },
  intro: {
    zh: '人称代词、y 和 en、泛指代词、指示词、主有词。镜子会把“我”变成“你”。点任何法语听发音。',
    en: 'Personal pronouns, y and en, indefinites, demonstratives, possessives. The mirror turns “I” into “you”. Click any French to hear it.',
  },

  opening: {
    title: ['Les', 'pronoms'],
    cover: ['Les pronoms'],
    floaters: ['moi', 'toi', 'lui', 'eux', 'y', 'en', 'le mien', 'celle-ci'],
    live: 'miroir',
    hint: { zh: '拖动旋转星球 · 点击镜子，听它把“我”说成“你”', en: 'Drag to turn the planet · tap the mirror to hear it turn “I” into “you”' },
  },

  /* ---------- 1. vocabulary ---------- */
  groups: [
    {
      id: 'sujets', emoji: '', title: { fr: 'Pronoms personnels sujets', zh: '人称代词·主语', en: 'Subject pronouns' },
      tip: { zh: '放在动词前做主语。on 口语里常代替 nous（On y va !），动词用第三人称单数。', en: 'They go before the verb. In speech, on often replaces nous (On y va!) and takes the third person singular.' },
      words: [
        { fr: 'je', zh: '我（主语）', en: 'I (subject)', note: { zh: '元音前省音：j’aime', en: 'j’ before a vowel: j’aime' } },
        { fr: 'tu', zh: '你（主语）', en: 'you (subject, informal)' },
        { fr: 'il', zh: '他；它（主语，阳）', en: 'he; it (subject, masc.)' },
        { fr: 'elle', zh: '她；它（主语，阴）', en: 'she; it (subject, fem.)' },
        { fr: 'on', zh: '人们；我们（主语，口语）', en: 'one; we (subject, spoken)' },
        { fr: 'nous', zh: '我们（主语）', en: 'we (subject)' },
        { fr: 'vous', zh: '你们；您（主语）', en: 'you (subject, plural / polite)' },
        { fr: 'ils', zh: '他们（主语）', en: 'they (subject, masc. or mixed)' },
        { fr: 'elles', zh: '她们（主语）', en: 'they (subject, all fem.)' },
      ],
    },
    {
      id: 'toniques', emoji: '', title: { fr: 'Pronoms personnels toniques', zh: '人称代词·重读', en: 'Stressed pronouns' },
      tip: { zh: '用在介词后（avec moi, chez toi）、c’est 后（C’est lui.）、单独回答或强调（Moi, je suis étudiant.）。', en: 'After a preposition (avec moi, chez toi), after c’est (C’est lui.), alone or for emphasis (Moi, je suis étudiant.).' },
      words: [
        { fr: 'moi', zh: '我（重读）', en: 'me (stressed)' },
        { fr: 'toi', zh: '你（重读）', en: 'you (stressed)' },
        { fr: 'lui', zh: '他（重读）', en: 'him (stressed)' },
        { fr: 'elle', zh: '她（重读）', en: 'her (stressed)' },
        { fr: 'nous', zh: '我们（重读）', en: 'us (stressed)' },
        { fr: 'vous', zh: '你们；您（重读）', en: 'you (stressed, plural / polite)' },
        { fr: 'eux', zh: '他们（重读）', en: 'them (stressed, masc.)' },
        { fr: 'elles', zh: '她们（重读）', en: 'them (stressed, fem.)' },
      ],
    },
    {
      id: 'cod', emoji: '', title: { fr: 'Pronoms compléments d’objet direct', zh: '人称代词·直接宾语', en: 'Direct object pronouns' },
      tip: { zh: '替代动词后直接跟的人或物（不带介词），放在动词前：Je vois Marie. → Je la vois. me、te、le、la 在元音前省音：m’、t’、l’。', en: 'They replace a person or thing that follows the verb directly (no preposition) and go before the verb: Je vois Marie. → Je la vois. Me, te, le, la become m’, t’, l’ before a vowel.' },
      words: [
        { fr: 'me', zh: '我（直接宾语）', en: 'me (direct object)', note: { zh: '元音前 m’：Il m’écoute.', en: 'm’ before a vowel: Il m’écoute.' } },
        { fr: 'te', zh: '你（直接宾语）', en: 'you (direct object)', note: { zh: '元音前 t’', en: 't’ before a vowel' } },
        { fr: 'le', zh: '他；它（直接宾语，阳）', en: 'him; it (direct object, masc.)', note: { zh: '元音前 l’：Je l’aime.', en: 'l’ before a vowel: Je l’aime.' } },
        { fr: 'la', zh: '她；它（直接宾语，阴）', en: 'her; it (direct object, fem.)', note: { zh: '元音前 l’', en: 'l’ before a vowel' } },
        { fr: 'nous', zh: '我们（直接宾语）', en: 'us (direct object)' },
        { fr: 'vous', zh: '你们；您（直接宾语）', en: 'you (direct object, plural / polite)' },
        { fr: 'les', zh: '他们；她们；它们（直接宾语）', en: 'them (direct object)' },
      ],
    },
    {
      id: 'coi', emoji: '', title: { fr: 'Pronoms compléments d’objet indirect', zh: '人称代词·间接宾语', en: 'Indirect object pronouns' },
      tip: { zh: '替代 à + 人，放在动词前：Je parle à Paul. → Je lui parle. lui 指他或她；leur 作代词时不加 s。', en: 'They replace à + a person and go before the verb: Je parle à Paul. → Je lui parle. Lui means him or her; leur as a pronoun never takes an s.' },
      words: [
        { fr: 'me', zh: '对我；给我（间接宾语）', en: 'to me (indirect object)' },
        { fr: 'te', zh: '对你；给你（间接宾语）', en: 'to you (indirect object)' },
        { fr: 'lui', zh: '对他／她；给他／她（间接宾语）', en: 'to him / to her (indirect object)' },
        { fr: 'nous', zh: '对我们（间接宾语）', en: 'to us (indirect object)' },
        { fr: 'vous', zh: '对你们；对您（间接宾语）', en: 'to you (indirect object, plural / polite)' },
        { fr: 'leur', zh: '对他们；给他们（间接宾语）', en: 'to them (indirect object)' },
      ],
    },
    {
      id: 'indefinis', emoji: '', title: { fr: 'Pronoms indéfinis', zh: '泛指代词', en: 'Indefinite pronouns' },
      tip: { zh: '都用第三人称单数的动词：Chacun a son livre. On parle français ici.', en: 'All take a third-person singular verb: Chacun a son livre. On parle français ici.' },
      words: [
        { fr: 'on', zh: '人们；有人；我们（泛指）', en: 'people; someone; we (indefinite)' },
        { fr: "quelqu'un", zh: '某人；有人', en: 'someone' },
        { fr: 'quelque chose', zh: '某物；某事', en: 'something' },
        { fr: 'chacun', zh: '每个人；每一个（阳）', en: 'each one; everyone (masc.)' },
        { fr: 'chacune', zh: '每一个（阴）', en: 'each one (fem.)' },
      ],
    },
    {
      id: 'y-en', emoji: '', title: { fr: 'Pronoms adverbiaux : y et en', zh: '副代词 y 和 en', en: 'Adverbial pronouns: y and en' },
      tip: { zh: 'y 替代地点或 à + 事物：J’y vais. en 替代 de + 事物或数量：J’en ai deux. 都放在动词前。', en: 'Y replaces a place or à + a thing: J’y vais. En replaces de + a thing, or a quantity: J’en ai deux. Both go before the verb.' },
      words: [
        { fr: 'y', zh: '那里；对此（替代 à + 事物／地点）', en: 'there; about it (replaces à + thing / a place)' },
        { fr: 'en', zh: '一些；其中的；关于这个（替代 de + 事物）', en: 'some; of it; about it (replaces de + thing)' },
      ],
    },
    {
      id: 'demonstratifs', emoji: '', title: { fr: 'Pronoms démonstratifs', zh: '指示代词', en: 'Demonstrative pronouns' },
      tip: { zh: '中性：ce（c’est）、cela、ça。个体指示代词替代名词，要接 de、qui 或 -ci / -là：celui de Paul，celle-ci。', en: 'Neuter: ce (c’est), cela, ça. The others replace a noun and need de, qui or -ci / -là: celui de Paul, celle-ci.' },
      words: [
        { fr: 'ce', zh: '这；那（中性，c’est）', en: 'it; this (neuter, c’est)', note: { zh: '多用在 être 前：c’est, ce sont', en: 'mostly before être: c’est, ce sont' } },
        { fr: 'cela', zh: '这；那（中性，书面）', en: 'this; that (neuter, written)' },
        { fr: 'ça', zh: '这；那（中性，口语）', en: 'this; that (neuter, spoken)' },
        { fr: 'celui', zh: '这个；那个（阳单）', en: 'this one / that one (masc. sing.)' },
        { fr: 'celle', zh: '这个；那个（阴单）', en: 'this one / that one (fem. sing.)' },
        { fr: 'ceux', zh: '这些；那些（阳复）', en: 'these / those (masc. plural)' },
        { fr: 'celles', zh: '这些；那些（阴复）', en: 'these / those (fem. plural)' },
      ],
    },
    {
      id: 'adj-demonstratifs', emoji: '', title: { fr: 'Adjectifs démonstratifs', zh: '指示形容词', en: 'Demonstrative adjectives' },
      tip: { zh: '放在名词前，和名词性数配合。cet 用于元音或哑音 h 开头的阳性单数名词：cet ami, cet hôtel。', en: 'They go before a noun and agree with it. Cet is for a masculine singular noun starting with a vowel or mute h: cet ami, cet hôtel.' },
      words: [
        { fr: 'ce', zh: '这个；那个（阳单，名词前）', en: 'this / that (masc. sing., before a noun)', note: { zh: 'ce livre', en: 'ce livre' } },
        { fr: 'cet', zh: '这个；那个（阳单，元音前）', en: 'this / that (masc. sing., before a vowel)', note: { zh: 'cet ami', en: 'cet ami' } },
        { fr: 'cette', zh: '这个；那个（阴单）', en: 'this / that (fem. sing.)', note: { zh: 'cette école', en: 'cette école' } },
        { fr: 'ces', zh: '这些；那些（复数）', en: 'these / those (plural)', note: { zh: 'ces amis', en: 'ces amis' } },
      ],
    },
    {
      id: 'adj-possessifs', emoji: '', title: { fr: 'Adjectifs possessifs', zh: '主有形容词', en: 'Possessive adjectives' },
      tip: { zh: '跟被拥有的名词性数配合，不跟主人：sa mère 也可以是“他的妈妈”。阴性名词以元音开头时用 mon / ton / son：mon amie。', en: 'They agree with the thing owned, not the owner: sa mère can be “his mother”. Before a feminine noun starting with a vowel, use mon / ton / son: mon amie.' },
      words: [
        { fr: 'mon', zh: '我的（阳单）', en: 'my (masc. sing.)' },
        { fr: 'ma', zh: '我的（阴单）', en: 'my (fem. sing.)' },
        { fr: 'mes', zh: '我的（复数）', en: 'my (plural)' },
        { fr: 'ton', zh: '你的（阳单）', en: 'your (masc. sing.)' },
        { fr: 'ta', zh: '你的（阴单）', en: 'your (fem. sing.)' },
        { fr: 'tes', zh: '你的（复数）', en: 'your (plural)' },
        { fr: 'son', zh: '他的；她的（阳单）', en: 'his / her (masc. sing.)' },
        { fr: 'sa', zh: '他的；她的（阴单）', en: 'his / her (fem. sing.)' },
        { fr: 'ses', zh: '他的；她的（复数）', en: 'his / her (plural)' },
        { fr: 'notre', zh: '我们的（单数）', en: 'our (singular)' },
        { fr: 'nos', zh: '我们的（复数）', en: 'our (plural)' },
        { fr: 'votre', zh: '你们的；您的（单数）', en: 'your (singular, plural / polite owner)' },
        { fr: 'vos', zh: '你们的；您的（复数）', en: 'your (plural, plural / polite owner)' },
        { fr: 'leur', zh: '他们的（单数）', en: 'their (singular)' },
        { fr: 'leurs', zh: '他们的（复数）', en: 'their (plural)' },
      ],
    },
    {
      id: 'pronoms-possessifs', emoji: '', title: { fr: 'Pronoms possessifs', zh: '主有代词', en: 'Possessive pronouns' },
      tip: { zh: '主有代词 = 定冠词 + 主有形式，替代“主有形容词 + 名词”：mon livre → le mien。nôtre、vôtre 有长音符，notre、votre 没有。', en: 'Possessive pronoun = definite article + possessive form, replacing “possessive + noun”: mon livre → le mien. Nôtre and vôtre have a circumflex; notre and votre do not.' },
      words: [
        { fr: 'le mien', zh: '我的（阳单）', en: 'mine (masc. sing.)' },
        { fr: 'la mienne', zh: '我的（阴单）', en: 'mine (fem. sing.)' },
        { fr: 'les miens', zh: '我的（阳复）', en: 'mine (masc. plural)' },
        { fr: 'les miennes', zh: '我的（阴复）', en: 'mine (fem. plural)' },
        { fr: 'le tien', zh: '你的（阳单）', en: 'yours (masc. sing.)' },
        { fr: 'la tienne', zh: '你的（阴单）', en: 'yours (fem. sing.)' },
        { fr: 'les tiens', zh: '你的（阳复）', en: 'yours (masc. plural)' },
        { fr: 'les tiennes', zh: '你的（阴复）', en: 'yours (fem. plural)' },
        { fr: 'le sien', zh: '他的；她的（阳单）', en: 'his / hers (masc. sing.)' },
        { fr: 'la sienne', zh: '他的；她的（阴单）', en: 'his / hers (fem. sing.)' },
        { fr: 'les siens', zh: '他的；她的（阳复）', en: 'his / hers (masc. plural)' },
        { fr: 'les siennes', zh: '他的；她的（阴复）', en: 'his / hers (fem. plural)' },
        { fr: 'le nôtre', zh: '我们的（阳单）', en: 'ours (masc. sing.)' },
        { fr: 'la nôtre', zh: '我们的（阴单）', en: 'ours (fem. sing.)' },
        { fr: 'les nôtres', zh: '我们的（复数）', en: 'ours (plural)' },
        { fr: 'le vôtre', zh: '你们的；您的（阳单）', en: 'yours, plural / polite (masc. sing.)' },
        { fr: 'la vôtre', zh: '你们的；您的（阴单）', en: 'yours, plural / polite (fem. sing.)' },
        { fr: 'les vôtres', zh: '你们的；您的（复数）', en: 'yours, plural / polite (plural)' },
        { fr: 'le leur', zh: '他们的（阳单）', en: 'theirs (masc. sing.)' },
        { fr: 'la leur', zh: '他们的（阴单）', en: 'theirs (fem. sing.)' },
        { fr: 'les leurs', zh: '他们的（复数）', en: 'theirs (plural)' },
      ],
    },
  ],

  /* ---------- 2. rules ---------- */
  rules: [
    {
      emoji: '', title: { fr: 'Où va le pronom ?', zh: '代词放在哪里', en: 'Where the pronoun goes' },
      tip: { zh: '宾语代词、y、en 放在变位动词前；否定时 ne 在代词前，pas 在动词后。复合时态放在助动词前。', en: 'Object pronouns, y and en go before the conjugated verb. In the negative, ne comes before the pronoun and pas after the verb. In compound tenses, before the auxiliary.' },
      rows: [
        { fr: 'Je vois Marie. → Je la vois.', zh: '我看见玛丽。→ 我看见她。', en: 'I see Marie. → I see her.' },
        { fr: 'Je ne la vois pas.', zh: '我没看见她。', en: "I don't see her." },
        { fr: 'Elle téléphone à son père. → Elle lui téléphone.', zh: '她给她爸爸打电话。→ 她给他打电话。', en: 'She phones her father. → She phones him.' },
        { fr: "Je n'y vais pas.", zh: '我不去那里。', en: "I'm not going there." },
        { fr: "Je n'en ai pas.", zh: '我没有（这个）。', en: "I don't have any." },
        { fr: "Je l'ai vu.", zh: '我看见他了。', en: 'I saw him.' },
      ],
    },
    {
      emoji: '', title: { fr: "L'élision", zh: '省音', en: 'Elision' },
      tip: { zh: 'me、te、le、la 在元音或哑音 h 前变成 m’、t’、l’。lui、leur、les 不省音。', en: 'Me, te, le, la become m’, t’, l’ before a vowel or mute h. Lui, leur and les never shorten.' },
      rows: [
        { fr: "Je l'aime.", zh: '我爱他／她。', en: 'I love him / her.' },
        { fr: "Il m'écoute.", zh: '他听我说。', en: 'He listens to me.' },
        { fr: "Je t'appelle ce soir.", zh: '我今晚给你打电话。', en: "I'll call you tonight." },
        { fr: 'Je les aime.', zh: '我爱他们。（les 不省音，连读 /z/）', en: 'I love them. (no elision; liaison /z/)' },
      ],
    },
    {
      emoji: '', title: { fr: 'Le miroir des personnes', zh: '镜子：我 ↔ 你', en: 'The mirror: I ↔ you' },
      tip: { zh: '回答问题时人称要“照镜子”：问句里的 tu / vous，回答变成 je / nous；te 变成 me。', en: 'When you answer, persons flip as in a mirror: tu / vous in the question become je / nous in the answer; te becomes me.' },
      rows: [
        { fr: 'Tu viens avec nous ? — Oui, je viens avec vous.', zh: '你和我们一起来吗？——对，我和你们一起去。', en: 'Are you coming with us? — Yes, I’m coming with you.' },
        { fr: 'Tu me téléphones ? — Oui, je te téléphone.', zh: '你给我打电话吗？——对，我给你打。', en: 'Will you phone me? — Yes, I’ll phone you.' },
        { fr: 'Vous parlez à vos parents ? — Oui, nous leur parlons.', zh: '你们跟父母说话吗？——对，我们跟他们说话。', en: 'Do you talk to your parents? — Yes, we talk to them.' },
        { fr: "C'est ton livre ? — Oui, c'est le mien.", zh: '这是你的书吗？——对，是我的。', en: 'Is it your book? — Yes, it’s mine.' },
      ],
    },
    {
      emoji: '', title: { fr: 'Ce, cet, celui-ci', zh: '指示词怎么选', en: 'Choosing a demonstrative' },
      tip: { zh: '名词前用 ce / cet / cette / ces；不说名词时用 celui / celle / ceux / celles + de / qui / -ci / -là。', en: 'Before a noun: ce / cet / cette / ces. Without the noun: celui / celle / ceux / celles + de / qui / -ci / -là.' },
      rows: [
        { fr: 'ce livre, cet hôtel, cette école, ces amis', zh: '这本书，这家酒店，这所学校，这些朋友', en: 'this book, this hotel, this school, these friends' },
        { fr: 'Quel livre tu veux ? — Celui-ci.', zh: '你要哪本书？——这本。', en: 'Which book do you want? — This one.' },
        { fr: 'Ma voiture et celle de mon père.', zh: '我的车和我爸爸的（车）。', en: 'My car and my father’s.' },
        { fr: 'Celle qui parle est ma sœur.', zh: '说话的那个是我姐姐。', en: 'The one who is speaking is my sister.' },
      ],
    },
  ],

  /* ---------- 3. questions and answers (yes and no) ---------- */
  questions: [
    { word: 'Qui ?', zh: '谁', en: 'Who?',
      q: { fr: 'Qui est là ?', zh: '谁在那儿？', en: "Who's there?" },
      a: [{ fr: "C'est moi.", zh: '是我。', en: "It's me." }] },
    { word: 'avec nous', zh: '和我们', en: 'with us',
      q: { fr: 'Tu viens avec nous ?', zh: '你和我们一起来吗？', en: 'Are you coming with us?' },
      a: [{ fr: 'Oui, je viens avec vous.', zh: '对，我和你们一起去。', en: 'Yes, I’m coming with you.' },
          { fr: 'Non, je ne viens pas avec vous.', zh: '不，我不和你们去。', en: 'No, I’m not coming with you.' }] },
    { word: 'le / la', zh: '他／她／它', en: 'him / her / it',
      q: { fr: 'Tu connais Marie ?', zh: '你认识玛丽吗？', en: 'Do you know Marie?' },
      a: [{ fr: 'Oui, je la connais.', zh: '对，我认识她。', en: 'Yes, I know her.' },
          { fr: 'Non, je ne la connais pas.', zh: '不，我不认识她。', en: "No, I don't know her." }] },
    { word: "l'", zh: '它（元音前）', en: 'it (before a vowel)',
      q: { fr: 'Tu aimes le café ?', zh: '你喜欢咖啡吗？', en: 'Do you like coffee?' },
      a: [{ fr: "Oui, je l'aime.", zh: '对，我喜欢。', en: 'Yes, I like it.' },
          { fr: "Non, je ne l'aime pas.", zh: '不，我不喜欢。', en: "No, I don't like it." }] },
    { word: 'me → te', zh: '我 → 你', en: 'me → you',
      q: { fr: 'Tu me téléphones ce soir ?', zh: '你今晚给我打电话吗？', en: 'Will you phone me tonight?' },
      a: [{ fr: 'Oui, je te téléphone.', zh: '对，我给你打。', en: 'Yes, I’ll phone you.' },
          { fr: 'Non, je ne te téléphone pas.', zh: '不，我不给你打。', en: 'No, I won’t phone you.' }] },
    { word: 'lui', zh: '对他／她', en: 'to him / her',
      q: { fr: 'Tu parles à ton père ?', zh: '你和你父亲说话吗？', en: 'Do you talk to your father?' },
      a: [{ fr: 'Oui, je lui parle.', zh: '对，我跟他说话。', en: 'Yes, I talk to him.' },
          { fr: 'Non, je ne lui parle pas.', zh: '不，我不跟他说话。', en: "No, I don't talk to him." }] },
    { word: 'leur', zh: '对他们', en: 'to them',
      q: { fr: 'Vous parlez à vos parents ?', zh: '你们和父母说话吗？', en: 'Do you talk to your parents?' },
      a: [{ fr: 'Oui, nous leur parlons.', zh: '对，我们跟他们说话。', en: 'Yes, we talk to them.' },
          { fr: 'Non, nous ne leur parlons pas.', zh: '不，我们不跟他们说话。', en: "No, we don't talk to them." }] },
    { word: 'y', zh: '那里', en: 'there',
      q: { fr: "Tu vas à l'école ?", zh: '你去学校吗？', en: 'Are you going to school?' },
      a: [{ fr: "Oui, j'y vais.", zh: '对，我去。', en: 'Yes, I’m going (there).' },
          { fr: "Non, je n'y vais pas.", zh: '不，我不去。', en: "No, I'm not going (there)." }] },
    { word: 'y (à …)', zh: '对此', en: 'about it',
      q: { fr: 'Il pense à son examen ?', zh: '他在想他的考试吗？', en: 'Is he thinking about his exam?' },
      a: [{ fr: 'Oui, il y pense.', zh: '对，他在想。', en: 'Yes, he’s thinking about it.' },
          { fr: "Non, il n'y pense pas.", zh: '不，他没在想。', en: "No, he isn't thinking about it." }] },
    { word: 'en', zh: '其中的', en: 'of them',
      q: { fr: 'Tu as des frères et sœurs ?', zh: '你有兄弟姐妹吗？', en: 'Do you have brothers and sisters?' },
      a: [{ fr: "Oui, j'en ai deux.", zh: '对，我有两个。', en: 'Yes, I have two.' },
          { fr: "Non, je n'en ai pas.", zh: '不，我没有。', en: "No, I don't have any." }] },
    { word: 'en (de …)', zh: '关于这个', en: 'about it',
      q: { fr: 'Elle parle de son travail ?', zh: '她谈她的工作吗？', en: 'Does she talk about her work?' },
      a: [{ fr: 'Oui, elle en parle.', zh: '对，她谈。', en: 'Yes, she talks about it.' },
          { fr: "Non, elle n'en parle pas.", zh: '不，她不谈。', en: "No, she doesn't talk about it." }] },
    { word: 'Lequel ?', zh: '哪一个', en: 'Which one?',
      q: { fr: 'Quel livre tu veux ?', zh: '你要哪本书？', en: 'Which book do you want?' },
      a: [{ fr: 'Celui-ci. / Celui-là.', zh: '这本。／那本。', en: 'This one. / That one.' }] },
    { word: 'À qui ?', zh: '谁的', en: 'Whose?',
      q: { fr: "C'est à qui, ce sac ?", zh: '这包是谁的？', en: 'Whose bag is this?' },
      a: [{ fr: "C'est à moi. / C'est le sien.", zh: '是我的。／是他的。', en: "It's mine. / It's his." }] },
    { word: 'le mien', zh: '我的', en: 'mine',
      q: { fr: "C'est ton livre ?", zh: '这是你的书吗？', en: 'Is this your book?' },
      a: [{ fr: "Oui, c'est le mien.", zh: '对，是我的。', en: "Yes, it's mine." },
          { fr: "Non, ce n'est pas le mien.", zh: '不，不是我的。', en: "No, it's not mine." }] },
    { word: 'les miennes', zh: '我的（复数）', en: 'mine (plural)',
      q: { fr: 'Ces clés sont à toi ?', zh: '这些钥匙是你的吗？', en: 'Are these keys yours?' },
      a: [{ fr: 'Oui, ce sont les miennes.', zh: '对，是我的。', en: 'Yes, they’re mine.' },
          { fr: 'Non, ce ne sont pas les miennes.', zh: '不，不是我的。', en: "No, they're not mine." }] },
  ],

  /* ---------- 4. verbs ---------- */
  verbs: [
    { inf: 'voir', ex: { fr: 'Je la vois.', zh: '我看见她。', en: 'I see her.' } },
    { inf: 'connaître', ex: { fr: 'Tu la connais ?', zh: '你认识她吗？', en: 'Do you know her?' } },
    { inf: 'aimer', ex: { fr: "Je l'aime.", zh: '我爱他。', en: 'I love him.' } },
    { inf: 'parler', ex: { fr: 'Nous leur parlons.', zh: '我们跟他们说话。', en: 'We talk to them.' } },
    { inf: 'téléphoner', ex: { fr: 'Elle lui téléphone.', zh: '她给他打电话。', en: 'She phones him.' } },
    { inf: 'donner', ex: { fr: 'Je te donne un cadeau.', zh: '我送你一份礼物。', en: 'I give you a present.' } },
    { inf: 'expliquer', ex: { fr: 'Elle nous explique la leçon.', zh: '她给我们讲解课文。', en: 'She explains the lesson to us.' } },
    { inf: 'penser', ex: { fr: 'Il y pense.', zh: '他在想这件事。', en: "He's thinking about it." } },
    { inf: 'écouter', ex: { fr: "Il m'écoute.", zh: '他听我说。', en: 'He listens to me.' } },
    { inf: 'aller', ex: { fr: "J'y vais.", zh: '我去那里。', en: "I'm going there." } },
  ],

  widgets: ['miroir'],
  quizExtras: ['pronoms'],

  proverbs: [
    { fr: 'Chacun son goût.', zh: '各有所好。', en: 'To each their own.' },
    { fr: 'Aide-toi, le ciel t’aidera.', zh: '自助者天助。', en: 'Heaven helps those who help themselves.' },
    { fr: 'Qui m’aime me suive.', zh: '爱我的人就跟我来。', en: 'Who loves me, follow me.' },
    { fr: 'À chacun son métier.', zh: '术业有专攻。', en: 'Let every man do his own trade.' },
    { fr: 'On n’est jamais si bien servi que par soi-même.', zh: '求人不如求己。', en: 'If you want something done well, do it yourself.' },
  ],

  /* ---------- 5. story ---------- */
  story: {
    title: { fr: 'La Dame aux miroirs', zh: '镜子夫人', en: 'The Lady of Mirrors' },
    scenes: [
      { emoji: '', bg: 'morning', fr: 'Sur une petite planète, une dame vit avec ses miroirs.', zh: '在一颗小星球上，一位夫人和她的镜子们住在一起。', en: 'On a small planet, a lady lives with her mirrors.' },
      { emoji: '', bg: 'morning', fr: 'Léa arrive. « Qui est là ? » demande la dame. « C’est moi, Léa ! »', zh: 'Léa 来了。“谁在那儿？”夫人问。“是我，Léa！”', en: 'Léa arrives. “Who’s there?” asks the lady. “It’s me, Léa!”' },
      { emoji: '', bg: 'noon', fr: 'La dame regarde son miroir. « Je me vois. Et toi, tu te vois ? »', zh: '夫人照着镜子。“我看见我自己。那你呢，你看见你自己吗？”', en: 'The lady looks in her mirror. “I see myself. And you, do you see yourself?”' },
      { emoji: '', bg: 'noon', fr: '« Oui, je me vois. Mais dans le miroir, moi, je deviens toi ! »', zh: '“看见了。可是在镜子里，我变成了你！”', en: '“Yes, I see myself. But in the mirror, I become you!”' },
      { emoji: '', bg: 'afternoon', fr: '« Ce miroir est à toi ? » « Non, ce n’est pas le mien. C’est le sien. »', zh: '“这面镜子是你的吗？”“不，不是我的，是她的。”', en: '“Is this mirror yours?” “No, it’s not mine. It’s hers.”' },
      { emoji: '', bg: 'afternoon', fr: '« Tu as des miroirs chez toi ? » « Oui, j’en ai deux. »', zh: '“你家有镜子吗？”“有，我有两面。”', en: '“Do you have mirrors at home?” “Yes, I have two.”' },
      { emoji: '', bg: 'evening', fr: '« Tu vas sur ta planète ce soir ? » « Oui, j’y vais. Je te téléphone demain. »', zh: '“你今晚回你的星球吗？”“对，我回去。明天给你打电话。”', en: '“Are you going to your planet tonight?” “Yes, I’m going. I’ll phone you tomorrow.”' },
      { emoji: '', bg: 'night', fr: '« Chacun a son miroir, » dit la dame, « mais on se voit mieux dans les yeux d’un ami. »', zh: '“每个人都有自己的镜子，”夫人说，“可是在朋友的眼睛里，才看得更清楚。”', en: '“Everyone has their own mirror,” says the lady, “but you see yourself better in a friend’s eyes.”' },
    ],
  },
});
